# Site settings
title: Il Prof Bicromatico
email: riccardo.giannitrapani@liceomarinelli.it
description: > # this means to ignore newlines until "baseurl:"
       "Su ciò di cui non si può parlare, si deve tacere."
       
       L.Wittgenstein
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://orporick.github.io" # the base hostname & protocol for your site
twitter_username: orporick
gplus_username: RiccardoGiannitrapani
github_username:  orporick

# Build settings
markdown: kramdown
kramdown:
        extensions: ["footnotes"]
permalink: pretty

collections:
        tracce:
                output: true
        soluzioni:
                output: true

