baseURL = 'https://orporick.github.io/'
languageCode = 'en-us'
title = 'Matematichevole'
theme = 'PaperMod'


enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

paginate=10 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	subtitle = "Pensieri sfusi di una mente confusa"
  katex = true # enable MathJax support
  ShowReadingTime= true
  ShowPostNavLinks= true
  ShowBreadCrumbs= true
  ShowWordCount= true
  ShowRssButtonInSectionTermList= true
  hideSummary = false

[params.profileMode]
  enabled=true
  title="Matematichevole"
  subtitle="Pensieri sfusi di una mente confusa"
  #imageUrl="https://avatars.githubusercontent.com/u/611834?v=4"  
  imageUrl="images/profilo1.jpg"
  imageWidth = 250
  imageHeight = 250
  Content = """Mi chiamo Riccardo Giannitrapani e insegno matematica e fisica in un Liceo Scientifico.\n

Raccolgo qui **[un po' di idee e di materiali](/posts)** in ordine sparso sull'insegnamento, la matematica, la fisica, i miei gatti, le mie piccole e gigantesche ossessioni.\n

Se non nel contenuto, lo spirito di queste idee è confluito, almeno parzialmente, in un libro: **[Un Labirinto Incerto. Appunti per una poetica della matematica](https://www.mondadori.it/libri/un-labirinto-incerto-riccardo-giannitrapani/)** edito da Mondadori.\
  """

[[params.socialIcons]]
name = "Email"
icon = "xda"
url = "https://twitter.com/orporick/"

[[params.socialIcons]]
name = "cv"
icon = "cv"
url = "cv.pdf"

[[params.socialIcons]]
name = "GitHub"
icon = "github"
url = "https://github.com/orporick"

[[params.socialIcons]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/orporick/"

[[params.socialIcons]]
name = "Facebook"
icon = "facebook"
url = "https://facebook.com/riccardo.giannitrapani"


[[params.socialIcons]]
name = "GoogleScholar"
icon = "googlescholar"
url = "https://scholar.google.com/citations?hl=it&user=C6GtOKoAAAAJ"

[[params.socialIcons]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/orporick"

[[params.socialIcons]]
name = "YouTube"
icon = "youtube"
url = "https://youtube.com/@RiccardoGiannitrapani"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5
